version: "3.8"

services:
  db:
    image: pgvector/pgvector:pg16
    restart: always
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

  sonia:
    image: sonia:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - ${SONIA_PORT}:${SONIA_PORT}
      - 5555:5555
    environment:
      - PORT=${SONIA_PORT}
      - DATABASE_URL=${DOCKER_DATABASE_URL}
    depends_on:
      - db

volumes:
  pgdata:
