services:
  db:
    image: neo4j:latest
    ports:
      - 7687:7687
      - 7474:7474
    volumes:
      - data:/data
    env_file:
      - .env.neo4j
    environment:
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_db_tx__log_rotation_retention__policy=false
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1",
        ]
      interval: 15s
      timeout: 30s
      retries: 10

volumes:
  data:
